### Imports

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("pokemon.csv")

In [10]:
df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [20]:
df.isna().sum()

abilities              0
against_bug            0
against_dark           0
against_dragon         0
against_electric       0
against_fairy          0
against_fight          0
against_fire           0
against_flying         0
against_ghost          0
against_grass          0
against_ground         0
against_ice            0
against_normal         0
against_poison         0
against_psychic        0
against_rock           0
against_steel          0
against_water          0
attack                 0
base_egg_steps         0
base_happiness         0
base_total             0
capture_rate           0
classfication          0
defense                0
experience_growth      0
height_m              20
hp                     0
japanese_name          0
name                   0
percentage_male       98
pokedex_number         0
sp_attack              0
sp_defense             0
speed                  0
type1                  0
type2                384
weight_kg             20
generation             0
is_legendary           0
dtype: int64

In [23]:
df.describe

<bound method NDFrame.describe of                        abilities  against_bug  against_dark  against_dragon  \
0    ['Overgrow', 'Chlorophyll']         1.00           1.0             1.0
1    ['Overgrow', 'Chlorophyll']         1.00           1.0             1.0
2    ['Overgrow', 'Chlorophyll']         1.00           1.0             1.0
3       ['Blaze', 'Solar Power']         0.50           1.0             1.0
4       ['Blaze', 'Solar Power']         0.50           1.0             1.0
..                           ...          ...           ...             ...
796              ['Beast Boost']         0.25           1.0             0.5
797              ['Beast Boost']         1.00           1.0             0.5
798              ['Beast Boost']         2.00           0.5             2.0
799              ['Prism Armor']         2.00           2.0             1.0
800               ['Soul-Heart']         0.25           0.5             0.0

     against_electric  against_fairy  against_fight  against_fire  \
0                 0.5            0.5            0.5           2.0
1                 0.5            0.5            0.5           2.0
2                 0.5            0.5            0.5           2.0
3                 1.0            0.5            1.0           0.5
4                 1.0            0.5            1.0           0.5
..                ...            ...            ...           ...
796               2.0            0.5            1.0           2.0
797               0.5            0.5            2.0           4.0
798               0.5            4.0            2.0           0.5
799               1.0            1.0            0.5           1.0
800               1.0            0.5            1.0           2.0

     against_flying  against_ghost  ...  percentage_male  pokedex_number  \
0               2.0            1.0  ...             88.1               1
1               2.0            1.0  ...             88.1               2
2               2.0            1.0  ...             88.1               3
3               1.0            1.0  ...             88.1               4
4               1.0            1.0  ...             88.1               5
..              ...            ...  ...              ...             ...
796             0.5            1.0  ...              NaN             797
797             1.0            1.0  ...              NaN             798
798             1.0            0.5  ...              NaN             799
799             1.0            2.0  ...              NaN             800
800             0.5            1.0  ...              NaN             801

     sp_attack  sp_defense  speed    type1   type2  weight_kg  generation  \
0           65          65     45    grass  poison        6.9           1
1           80          80     60    grass  poison       13.0           1
2          122         120     80    grass  poison      100.0           1
3           60          50     65     fire     NaN        8.5           1
4           80          65     80     fire     NaN       19.0           1
..         ...         ...    ...      ...     ...        ...         ...
796        107         101     61    steel  flying      999.9           7
797         59          31    109    grass   steel        0.1           7
798         97          53     43     dark  dragon      888.0           7
799        127          89     79  psychic     NaN      230.0           7
800        130         115     65    steel   fairy       80.5           7

     is_legendary
0               0
1               0
2               0
3               0
4               0
..            ...
796             1
797             1
798             1
799             1
800             1

[801 rows x 41 columns]>

In [25]:
eda = df.describe()
eda.T

,count,mean,std,min,25%,50%,75%,max
against_bug,801.0,9.962547e-01,0.597248,0.25,0.5,1.0,1.0,4.0
against_dark,801.0,1.057116e+00,0.438142,0.25,1.0,1.0,1.0,4.0
against_dragon,801.0,9.687890e-01,0.353058,0.00,1.0,1.0,1.0,2.0
against_electric,801.0,1.073970e+00,0.654962,0.00,0.5,1.0,1.0,4.0
against_fairy,801.0,1.068976e+00,0.522167,0.25,1.0,1.0,1.0,4.0
against_fight,801.0,1.065543e+00,0.717251,0.00,0.5,1.0,1.0,4.0
against_fire,801.0,1.135456e+00,0.691853,0.25,0.5,1.0,2.0,4.0
against_flying,801.0,1.192884e+00,0.604488,0.25,1.0,1.0,1.0,4.0
against_ghost,801.0,9.850187e-01,0.558256,0.00,1.0,1.0,1.0,4.0
against_grass,801.0,1.034020e+00,0.788896,0.25,0.5,1.0,1.0,4.0
against_ground,801.0,1.098002e+00,0.738818,0.00,1.0,1.0,1.0,4.0
against_ice,801.0,1.208177e+00,0.735356,0.25,0.5,1.0,2.0,4.0
against_normal,801.0,8.870162e-01,0.266106,0.00,1.0,1.0,1.0,1.0
against_poison,801.0,9.753433e-01,0.549375,0.00,0.5,1.0,1.0,4.0
against_psychic,801.0,1.005306e+00,0.495183,0.00,1.0,1.0,1.0,4.0
against_rock,801.0,1.250312e+00,0.697148,0.25,1.0,1.0,2.0,4.0
against_steel,801.0,9.834582e-01,0.500117,0.25,0.5,1.0,1.0,4.0
against_water,801.0,1.058365e+00,0.606562,0.25,0.5,1.0,1.0,4.0
attack,801.0,7.785768e+01,32.158820,5.00,55.0,75.0,100.0,185.0
base_egg_steps,801.0,7.191011e+03,6558.220422,1280.00,5120.0,5120.0,6400.0,30720.0
base_happiness,801.0,6.536205e+01,19.598948,0.00,70.0,70.0,70.0,140.0
base_total,801.0,4.283770e+02,119.203577,180.00,320.0,435.0,505.0,780.0
defense,801.0,7.300874e+01,30.769159,5.00,50.0,70.0,90.0,230.0
experience_growth,801.0,1.054996e+06,160255.835096,600000.00,1000000.0,1000000.0,1059860.0,1640000.0
height_m,781.0,1.163892e+00,1.080326,0.10,0.6,1.0,1.5,14.5
hp,801.0,6.895880e+01,26.576015,1.00,50.0,65.0,80.0,255.0
percentage_male,703.0,5.515576e+01,20.261623,0.00,50.0,50.0,50.0,100.0
pokedex_number,801.0,4.010000e+02,231.373075,1.00,201.0,401.0,601.0,801.0
sp_attack,801.0,7.130587e+01,32.353826,10.00,45.0,65.0,91.0,194.0
sp_defense,801.0,7.091136e+01,27.942501,20.00,50.0,66.0,90.0,230.0
speed,801.0,6.633458e+01,28.907662,5.00,45.0,65.0,85.0,180.0
weight_kg,781.0,6.137810e+01,109.354766,0.10,9.0,27.3,64.8,999.9
generation,801.0,3.690387e+00,1.930420,1.00,2.0,4.0,5.0,7.0
is_legendary,801.0,8.739076e-02,0.282583,0.00,0.0,0.0,0.0,1.0